### ISSUE TITLE
The $gp is slightly off

### ISSUE THREAD

**Issue by water111** [beardypig/ghidra-emotionengine#1]
In a game where $gp should be $13ec70, ghidra is assuming it is $14ec70.

The "Register Manager" has

```
start        end         value
0x100008     0x100008    0x13ec70  ;; this is correct
0x1000b8     0x1000b8    0x14ec70
0x1000c0     0x1000c0    0x14ec70
...
```

**Comment by water111** [comment]
as an update, opening and closing the window a few times makes it start working as expected.

**Comment by beardypig** [comment]
Weird. Sounds like it could be a ghidra issue then :)

**Comment by water111** [comment]
I'm unable to replicate this, so I'm going to close the issue and assume it's a problem with myself or ghidra.
