### ISSUE TITLE
ghidra 9.0.4

### ISSUE THREAD

**Issue by bigianb** [beardypig/ghidra-emotionengine#14]
Any chance you can find time to make a release that works with 9.0.4? I guess it's just a version number bump but 9.0.4 refuses to install the current one.

**Comment by beardypig** [comment]
@bigianb I have updated the latest release with a build for 9.0.4, I haven't tested it - so let me know if it works, or not.

**Comment by bigianb** [comment]
it works -thank you.

**Comment by beardypig** [comment]
Thanks for reporting :) I need to work out how to set up automatic builds in GitHub flows or travis :)

**Comment by bigianb** [comment]
actually I may have spoken too soon - the decompiler throws an alignment error in 9.0.4. It could be a core issue of course unrelated to this extension. I'll dig a bit when I get time but until then have rolled back to 9.0.1 as there are no real changes with the new version.

**Comment by beardypig** [comment]
@bigianb I have rebuilt the packages for the latest version, if you're able to test to see if that resolves your issue with 9.0.4 that would be great :)

**Comment by aldelaro5** [comment]
Well, ghidra 9.1 BETA released and it completely broke the extension (as in, even if I change the properties to the version, it breaks when reading the sleigh). Seems like that version has had changes that breaks.

Should I open a new issue?

**Comment by VelocityRa** [comment]
This can be closed.
