### ISSUE TITLE
Create build for Ghidra 9.1

### ISSUE THREAD

**Issue by beardypig** [beardypig/ghidra-emotionengine#20]
Build the extension for for Ghidra 9.1.

**Comment by astrelsky** [comment]
9.1-DEV or 9.1-BETA? there is no java atm and ghidra now compiles sleigh upon loading the language.  Just changing the extension version number should be sufficient.

**Comment by atom0s** [comment]
Any chance to get https://github.com/beardypig/ghidra-emotionengine/pull/11 added too for the next build? 

_Thanks a ton for this plugin guys, been working with some PS2 ELFs lately and this is a lot of help. :)_

**Comment by aldelaro5** [comment]
is there an ETA on when this could be done? been messing with 2 ghidra in the mean time :(

**Comment by VelocityRa** [comment]
Any updates on this?

**Comment by Kneesnap** [comment]
I'd like a build for 9.1.1 if possible.

**Comment by VelocityRa** [comment]
This can be closed.
