### ISSUE TITLE
ghidra-emotionengine doesn't open! BAD MANUALS!!!

### ISSUE THREAD

**Issue by olejika** [beardypig/ghidra-emotionengine#29]
FAILURE: Build failed with an exception.

* Where:
Build file  'C:\Users\taras\Desktop\ghidra\EX\ghidra-emotionengine-master\build.gradle' line: 34

* What went wrong:
A problem occurred evaluating root project 'ghidra-emotionengine-master'.
GHIDRA_INSTALL_DIR is not defined!

*  Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more lag output.  Run with
--scan to get full insights.
* Get more help at  https://help.gradle.org

BUILD  FAILED in 1s

**Comment by beardypig** [comment]
You might have more luck downloading a [pre-compiled release](https://github.com/beardypig/ghidra-emotionengine/releases), however we have not released the latest version for the latest version of Ghidra.

However, the answer to your issue is in the error log you pasted, `GHIDRA_INSTALL_DIR is not defined`. You need to define `GHIDRA_INSTALL_DIR` to point to your Ghidra install directory. 

eg.
```
./gradlew -PGHIDRA_INSTALL_DIR=$HOME/ghidra_9.1 buildExtension
```

**Comment by olejika** [comment]
![ашипка](https://user-images.githubusercontent.com/15987321/70063522-fe418180-15f8-11ea-8ad9-0fe6f6f76b97.png)

**Comment by beardypig** [comment]
@olejika what command did you use to build it?

**Comment by olejika** [comment]
I pressed the plus sign and went to your folder

**Comment by beardypig** [comment]
~Unfortunately the current latest version is has not be compiled for Ghidra version 9.0.4 so it won't work. I will compile a new version and add it to the release.~

Edit: It was already available. Which version did you download? 

https://github.com/beardypig/ghidra-emotionengine/releases/download/v1.4.1/ghidra_9.0.4_PUBLIC_20190727_emotionengine.zip

That one should work, if not please report back that it does not work.

**Comment by astrelsky** [comment]
If you build it yourself with the command in the README won't need to worry about the extension version. However, if you download a prebuilt one you will need to select the correct version for the version of ghidra you have installed.

If you want to be lazy, you can just change the value of version in extension.properties to the version of ghidra you have installed.

If building it using the command in the README doesn't work then set the system environment variable GHIDRA_INSTALL_DIR to the ghidra installation directory then restart your terminal and just run `gradle buildExtension`

**Comment by VelocityRa** [comment]
No feedback, you can close this now.
