### ISSUE TITLE
Release for Ghidra 9.2

### ISSUE THREAD

**Issue by VelocityRa** [beardypig/ghidra-emotionengine#40]
Reposting my built release from #36 for people to use till this is handled with a proper Release on the repo:
[ghidra_9.2_PUBLIC_20201120_ghidra-emotionengine.zip](https://github.com/beardypig/ghidra-emotionengine/files/5571628/ghidra_9.2_PUBLIC_20201120_ghidra-emotionengine.zip)

**Comment by beardypig** [comment]
Thanks @VelocityRa, once #16 been merged we'll get a release out, only supporting 9.2+.

**Comment by VelocityRa** [comment]
Bump.
