### ISSUE TITLE
Release for Ghidra 9.2.2

### ISSUE THREAD

**Issue by VelocityRa** [beardypig/ghidra-emotionengine#49]
Posting this for people to use till it's handled with a proper Release on the repo:
[ghidra_9.2.2_PUBLIC_20210224_ghidra-emotionengine.zip](https://github.com/beardypig/ghidra-emotionengine/files/6038149/ghidra_9.2.2_PUBLIC_20210224_ghidra-emotionengine.zip)

**Comment by beardypig** [comment]
I will set up a Github action to build a "Latest" version of the plugin for the supported version of Ghidra.

**Comment by beardypig** [comment]
I have created that "[latest](https://github.com/beardypig/ghidra-emotionengine/releases/tag/latest)" release. It gets built once per day.

**Comment by Risae** [comment]
Both of you, thank you very much!
