### ISSUE TITLE
Integration into a development environment

### ISSUE THREAD

**Issue by jonyvalky** [beardypig/ghidra-emotionengine#50]
Hello, is it possible to integrate this project into a development environment?

If possible, what environment? Eclipse? along with Ghidra?

Or is it only possible to work manually and build by Gradle?

**Comment by VelocityRa** [comment]
Yes you can, see Ghidra's documentation for extension development.

**Comment by jonyvalky** [comment]
Ok, Is it possible to import this project?
Or do I have to create a new "Ghidra Module Project" and import the files manually?

![Ghidra1](https://user-images.githubusercontent.com/80225170/110341832-889d4000-8009-11eb-9db5-c6c42d9287f5.png)
