### ISSUE TITLE
float to integer conversion

### ISSUE THREAD

**Issue by mdecicco** [beardypig/ghidra-emotionengine#52]
This happens everywhere the `cvt.w.S` instruction is followed by the `mfc1` instruction. I'm not sure, but shouldn't this be decompiled to just `iVar25 = fVar38`?

![image](https://user-images.githubusercontent.com/9410375/116005952-4048da00-a5d7-11eb-8a71-0e277becc66f.png)

**Comment by Tupelov** [comment]
cvt.w.s fd, fs
Convert fs from float to integer and store result inside of fd
mfc1 rt, fs
Copy contents of floating point register fs to general purpose register gp

So its basically just casting the float as an int.
int ivar = (int)fvar;
You can't just make it equal to each other because you'll get a type error.

**Comment by mdecicco** [comment]
Thanks for the response. I made an error in my post, I should have typed `iVar25 = (int)fVar38` instead of `iVar25 = fVar38`. I just wonder why it must complicate the decompilation view with what you see on the right of my screenshot when it could maybe just be `iVar25 = (int)fVar38`. I'm attempting to reverse some physics code and some of the larger functions are littered with these.

**Comment by mdecicco** [comment]
For anyone else: I fixed it by changing this code and rebuilding and reinstalling the extension:
https://github.com/beardypig/ghidra-emotionengine/blob/master/data/languages/cop1.sinc#L117-L131
to just this:
```
# 0100 0110 0000 0000 ssss sddd dd10 0100
:cvt.w.S fd, fs             		is ft=0 & fct=36 & fd & fs & format=0x10 {
    fd = trunc(fs);
}
```

It's probably technically incorrect in that it might not mirror exactly what the PS2 does, but it's good enough for my purposes now that I can read the decompilation more easily.

**Comment by astrelsky** [comment]
The ps2 cop1 does truncate floats when converting to integer.

**Comment by Tupelov** [comment]
I'm not gonna post it here but if you search "EE Core Instruction Set Manual" on google with the quotes, you'll find the docs as the first result. And checking the docs says that it rounds to 0 so trunc would be correct. I think we should add this as a PR since it makes the code look cleaner.

**Comment by mdecicco** [comment]
Thanks for the input and the reference manual! I've submitted a [PR](https://github.com/beardypig/ghidra-emotionengine/pull/57).

**Comment by Tupelov** [comment]
Just for reference, there are other manuals for the ps2. I can't post but its better to know they do exist.
![image](https://user-images.githubusercontent.com/64274155/116403157-3d2e3380-a7fb-11eb-9278-2983e7c3b80d.png)
