### ISSUE TITLE
Signed value displayed in unsigned instruction

### ISSUE THREAD

**Issue by Tupelov** [beardypig/ghidra-emotionengine#53]
addiu Uses an unsigned value.
![image](https://user-images.githubusercontent.com/64274155/116084797-25747500-a66c-11eb-9fb0-7e978f056d93.png)
It should display:
addiu v0,v0 0xfd80
addiu v1,v1, 0xe330

**Comment by astrelsky** [comment]
Nice catch. May you change `simmed` to `immed` in [mips.sinc](https://www.github.com/beardypig/ghidra-emotionengine/tree/master/data%2Flanguages%2Fmips.sinc) on lines 24 and 25, change `sext` to `zext` on line 26, and then submit a pull request please? I'm on my phone and this is a simple fix that you should get credit for.

If you may also fix the `li` and `addu` instructions as well it would be appreciated. They are right below `addiu`.

**Comment by Tupelov** [comment]
I'll try checking it out, hopefully I don't need a Java IDE setup

**Comment by Tupelov** [comment]
Seems like this issue also affects a bunch of other immediate unsigned instructions as well, I'll try to fix those as well

**Comment by Tupelov** [comment]
Yeah looks like that fixed it.
![image](https://user-images.githubusercontent.com/64274155/116289241-51712280-a760-11eb-8e08-26b958ac9818.png)
I'll be submitting my fixes as a pr soon

**Comment by Tupelov** [comment]
Closed #55

**Comment by JayFoxRox** [comment]
> addiu Uses an unsigned value.

This is incorrect and a broken assumption for #55.

The only difference to `addi` is that it shouldn't cause overflow exceptions.
Otherwise it's exactly the same. There's plenty of literature on the topic, but https://webdocs.cs.ualberta.ca/~amaral/courses/229/F04/webslides/Topic6-Logic/tsld005.htm is a good summary.
