### ISSUE TITLE
Can't jump to location of gp register

### ISSUE THREAD

**Issue by Tupelov** [beardypig/ghidra-emotionengine#56]
![image](https://user-images.githubusercontent.com/64274155/116308577-a703fa00-a775-11eb-8927-d19afa88a0f0.png)

**Comment by astrelsky** [comment]
It's on the heap, there won't be anything there. If you wan't you can create an uninitialized memory block from the Ghidra user interface in the memory map window (`Window->Memory Map`). After creating it you should be able to go to the address.

**Comment by Tupelov** [comment]
Here I manually added a reference.
![image](https://user-images.githubusercontent.com/64274155/116327730-6ddb8200-a795-11eb-9e5c-efcf1cf106ac.png)
I dont think it would make sense for the heap to be referenced by gp since it's usually put in the middle of the data like so
![image](https://user-images.githubusercontent.com/64274155/116328063-273a5780-a796-11eb-95bd-cecfd4ff9af4.png)
The heap is usually started at the end of bss
![image](https://user-images.githubusercontent.com/64274155/116328283-af206180-a796-11eb-857b-aa46e68d3c39.png)
I don't mean any offense I just wanna clear misinformation :)

**Comment by astrelsky** [comment]
Oh. I misunderstood the issue when I saw the symbol in the output.

Have you run the constant propagation analyzer? If the magic gp symbol (I forget the actual name) is defined then it should automatically be taken care of during analysis. 

I actually thought that gp was the start of the heap. I've never reversed anything that actually used it so I just learned something new.

**Comment by Tupelov** [comment]
Yeah its used so that you can load address from memory in a single instruction as long as they are at a offset of−32,768 to 32,767 from gp using something like sw,lw etc. rather than use lui + addiu so it's pretty important when it comes to commercial stuff.

I can't actually find Constant propagation analysis inside my analyzer window and it seems that it wouldn't help in this situation as it seems to analyze pointing to addresses with multiple instructions and gp accesses are usually only done with one

**Comment by Tupelov** [comment]
Ok it seems like my eyes weren't working I found the option ._.
Looks like it fixed it although there are still some lieing around so I'll have to check more

**Comment by Tupelov** [comment]
I'll close this issue but for reference "MIPS-R5900 Constant Reference Analyzer" is what fixed it.
Thanks for the help :)

**Comment by astrelsky** [comment]
> I'll close this issue but for reference "MIPS-R5900 Constant Reference Analyzer" is what fixed it.
> Thanks for the help :)
> 
> 
> 

This analyzer should be enabled by default. Was this not the case?

**Comment by Tupelov** [comment]
Looks like it is on by default when I look at it. I'm not sure why it didn't work when I analyzed the file at the start. I've been having this issue over several versions of the extension (with different projects).
