### ISSUE TITLE
Issue with 'Error in plugin event listener'

### ISSUE THREAD

**Issue by GenericMadScientist** [beardypig/ghidra-emotionengine#61]
Whenever I try to open the Yu-Gi-Oh! The Duelists of the Roses Japanese ELF I get an 'Error in plugin event listener'. This happens even if I start a new project with said ELF and try to import it as a raw binary using the MIPS R5900 instruction set. [Here is said ELF](https://github.com/beardypig/ghidra-emotionengine/files/6491310/SLPM_650.zip)

**Comment by GenericMadScientist** [comment]
Okay, so it turns out the plugin is not to blame whatsoever. It turns out that Ghidra just doesn't want to behave with OpenJDK 16. Reverting to OpenJDK 15.0.2 solved the problem.

**Comment by rodg** [comment]
The fix mentioned in the closing comment here also worked (for me) if you want to stay on a newer JDK: https://github.com/NationalSecurityAgency/ghidra/issues/2999
