### ISSUE TITLE
EI/DI decompile improperly

### ISSUE THREAD

**Issue by PSI-Rockin** [beardypig/ghidra-emotionengine#7]
The EI and DI instructions modify bit 16 of the COP0 Status register, or the master interrupt enable. However, decompilation shows them as having the effect of `Status = Status & 0xFFFFFFFE` in the case of DI, which is incorrect.

A cleaner solution imo would be to decompile these instructions as EI() and DI() as if they were functions or macros.

**Comment by beardypig** [comment]
Much cleaner. Easily done too :)
