### ISSUE TITLE
ADDIU's immediate value isn't properly sign-extended.

### ISSUE THREAD

**Issue by GenericMadScientist** [beardypig/ghidra-emotionengine#8]
In the instruction `addiu v0, zero, 0xFFFF`, `v0` is supposed to end up with the value `0xFFFFFFFF` because the literal is sign-extended to a 32-bit value. However, Ghidra says it ends up with the value `0xFFFF`. This error does not happen with the version of MIPS that comes with Ghidra that I also checked this with.

**Comment by beardypig** [comment]
Hmm, not obvious why that isn't working.

The SLEIGH definition for `ADDIU` is this, which has a `sext` (sign extend) call to sign extend the 32bit result in to the 64 register `rt`... 
```
# 0010 01ss ssst tttt iiii iiii iiii iiii
:addiu RT32, RS32src, simmed            is prime=9 & RT32 & RS32src & simmed & RT {
    RT32 = RS32src + simmed;
    RT = sext(RT32);
}
```

**Comment by GenericMadScientist** [comment]
Hmm. The specific instruction I listed shows as a `LI`. In your SLEIGH code for `LI` you use `zext` instead, and use `immed` instead of `simmed`. Maybe that's the problem?

**Comment by beardypig** [comment]
That'll be it 👍 

Changing it to this might fix it - if you want to test it quickly, you can edit the `sinc` file and Ghidra will automatically recompile them when you open it (I think).
```
# 0010 0100 000t tttt iiii iiii iiii iiii
# special case of ADDIU
:li RT32, simmed                        is prime=9 & RT32 & rs=0 & simmed & RT {
    RT32 = sext(immed:2);
    RT = sext(RT32);
}
```

**Comment by GenericMadScientist** [comment]
Yep, that fixed it. A minor thing: in the line `RT32 = sext(immed:2)` you don't change to `simmed` (I assume that's a typo). I changed that to `simmed` as well and it works now.

**Comment by beardypig** [comment]
Yep, a typo :) Would you like to make a PR fox the fix?

**Comment by GenericMadScientist** [comment]
Done and fixed.

**Comment by beardypig** [comment]
Thanks for the issue and PR @GenericMadScientist :)
